set database sql syntax PGS true;
CREATE SCHEMA frog_room;

CREATE TABLE FROGS
(
    FROG_ID    SERIAL PRIMARY KEY,
    NAME    VARCHAR(30)   NOT NULL,
    LATIN_NAME     VARCHAR(80)   NOT NULL,
    DESCRIPTION       VARCHAR(50)   NOT NULL,
    GENDER  INTEGER NOT NULL,
    PHOTO BLOB   		NULL
);

CREATE TABLE FOODS
(
    FOOD_ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(80)   NOT NULL,
    LATIN_NAME VARCHAR(80) NOT NULL,
    DESCRIPTION VARCHAR(1024) NOT NULL,
    NUTRION      VARCHAR(1024)       NOT NULL
);

CREATE TABLE FROG_FOODS
(
    FROG_ID INTEGER NOT NULL REFERENCES FROGS (FROG_ID),
    FOOD_ID INTEGER NOT NULL REFERENCES FOODS (FOOD_ID)
);

